In [1]:
import numpy as np
import math

size = 5
a_matrix = []
with open('input.txt') as file:
    i = 0
    for line in file:
        a_matrix.append([float(x) for x in line.split(' ')])
        i += 1
a_matrix = np.array(a_matrix)
epsilon = 1e-5
# Симметричный вид
a_matrix = np.matmul(a_matrix.T, a_matrix)
# Начальное приближение
y_old = [0 for i in range(size - 1)]
y_old.append(1)
print("Начальное приближение:")
print(y_old)
y_new = np.matmul(a_matrix, y_old)
lambda_new = np.dot(y_new, y_old) / np.dot(y_old, y_old)
n = 0
while True:
    n += 1
    y_old = y_new
    lambda_old = lambda_new
    y_new = np.matmul(a_matrix, y_new)
    lambda_new = np.dot(y_new, y_old) / np.dot(y_old, y_old)
    if abs(lambda_new - lambda_old) <= epsilon:
        break
print("Число итераций: " + str(n))
print('Максимальное собственное значение:')
print(lambda_new)
print('Собственный вектор, соответствующий этому собственному значению:')
print(y_old)

Начальное приближение:
[0, 0, 0, 0, 1]
Число итераций: 9
Максимальное собственное значение:
1.1447499595770831
Собственный вектор, соответствующий этому собственному значению:
[ 1.29976058  0.18863179  0.94458672 -0.44767659  1.85494189]


In [2]:
# Невязка для собственного значения и собственного вектора
res = np.matmul(a_matrix, y_old) - lambda_new * y_old
print(res)
print('Норма невязки: ', end='')
print(format(np.linalg.norm(res, 2), '.4e'))

[-0.00034888 -0.00244649  0.00111387 -0.00198575 -0.00055321]
Норма невязки: 3.4054e-03


In [4]:
# Невязка для собственного значения и собственного вектора
res = np.matmul(a_matrix, y_old) - 1.144756197021018 * y_old
print(res)
print('Норма невязки: ', end='')
print(format(np.linalg.norm(res, 2), '.4e'))

[-0.00035698 -0.00244767  0.00110798 -0.00198296 -0.00056478]
Норма невязки: 3.4055e-03


In [3]:
# Невязка для собственного значения
# Из метода Данилевского
p = [3.1966884499999972, -3.7968475734971836, 2.0678062361750578, -0.5082483413019262, 0.044096040836178144]
sum = pow(lambda_new, size)
for j in reversed(range(size)):
    sum -= pow(lambda_new, j) * p[size - j - 1]
print(format(sum, '.4e'))

-6.5667e-07
